version: "3"

services:
    blogger_service:
        image: webdevops/php-nginx-dev:8.1
        # platform: linux/x86_64
        ports:
            - 8080:80
        working_dir: /app
        environment: 
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_MEMORY_LIMIT=512M
            - PHP_MAX_EXECUTION_TIME=30
            - PHP_POST_MAX_SIZE=20M
            - PHP_UPLOAD_MAX_FILESIZE=20M
        volumes:
            - './app:/app'
    ci4_DB:
        image: mysql:5.7
        # platform: linux/x86_64
        environment:
            MYSQL_DATABASE: blogger
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
    ci4_test_DB:
        image: mysql:5.7
        # platform: linux/x86_64
        environment:
            MYSQL_DATABASE: blogger
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
